### PR TITLE
US 1624627 - Rebranding for Azure Machine Learning

### PR DESCRIPTION
**Pull request by craigcaseyMSFT**
Rebranding of Azure Machine Learning per User Story https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1624627.

### CODE REVIEW

**Comment by craigcaseyMSFT** [comment]
@PeterCLu - Hi, Peter. Just one rebranding done for this repo. Please review and let me know if we're OK to merge. (I'll have to resolve the Warnings in files I didn't touch with the PR Reviewers). 

Thanks!

**Comment by PeterCLu** [comment]
@craigcaseyMSFT , approved!

**Comment by craigcaseyMSFT** [comment]
#sign-off

**Comment by craigcaseyMSFT** [comment]
@scbedd  - We are rebranding Azure Machine Learning per User Story https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1624627 and found an occurrence in this repo that needed to be changed. Would you please be able to merge this PR for us, or let me know who I should/can contact? **NOTE:** You can see that we received some warnings for files we didn't make any changes to.

Thanks for your help!

**Comment by scbedd** [comment]
Rationale seems reasonable to me. Note that this won't bring the changes live immediately. I've got more doc changes incoming tomorrow or the next day. Your changes to merge to `live` (and be visible) by the end of the week.

**Pull request merged**
