### PR TITLE
Fix the broken link in NGINX sdk document.

### PR DESCRIPTION
**Pull request by limingu**

### CODE REVIEW

**Comment by JimSuplizio** [comment]
@limingu - It's odd that these samples are linking to another repository and not to specific SHA or tag. That seems like it would be more resilient to changes in that repository if it were looking at the samples which were valid at the time the libraries were released. This is especially true if you're changing the libraries themself and then having to change the samples to go with them.

**Review by JimSuplizio — CHANGES_REQUESTED** [review]
You're updating the Nginx overview to fix the links but the Overview page for the [azure.mgmt.nginx](https://learn.microsoft.com/en-us/python/api/overview/azure/mgmt-nginx-readme?view=azure-python#examples) still has the wrong link. The [Preview version's overview page](https://learn.microsoft.com/en-us/python/api/overview/azure/mgmt-nginx-readme?view=azure-python-preview#examples), since it was released this year, _after_ you'd updated the samples repository, is correct. The additional file that needs to be updated is the Other Nginx Management doc link in [docs-ref-services/latest/mgmt-nginx-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/mgmt-nginx-readme.md).

**Review by danieljurek — APPROVED** [review]

**Comment by limingu** [comment]
> @limingu - It's odd that these samples are linking to another repository and not to specific SHA or tag. That seems like it would be more resilient to changes in that repository if it were looking at the samples which were valid at the time the libraries were released. This is especially true if you're changing the libraries themself and then having to change the samples to go with them.

F5(external company) owns NGINX. They put the samples in their repository. They updated there and caused this error.

**Comment by limingu** [comment]
> You're updating the Nginx overview to fix the links but the Overview page for the [azure.mgmt.nginx](https://learn.microsoft.com/en-us/python/api/overview/azure/mgmt-nginx-readme?view=azure-python#examples) still has the wrong link. The [Preview version's overview page](https://learn.microsoft.com/en-us/python/api/overview/azure/mgmt-nginx-readme?view=azure-python-preview#examples), since it was released this year, _after_ you'd updated the samples repository, is correct. The additional file that needs to be updated is the Other Nginx Management doc link in [docs-ref-services/latest/mgmt-nginx-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/mgmt-nginx-readme.md).

Thank you @JimSuplizio! I updated the other Nginx Management doc link in [docs-ref-services/latest/mgmt-nginx-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/mgmt-nginx-readme.md).

**Review by JimSuplizio — APPROVED** [review]

**Comment by JimSuplizio** [comment]
@limingu I see that you updated the other Nginx Management doc link in [docs-ref-services/latest/mgmt-nginx-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/mgmt-nginx-readme.md), thank you. All of the checks have passed and I'll merge the pull request for you. The documentation updates should be on the live site Monday morning (it's updated every morning M-F now).

**Comment by limingu** [comment]
> @limingu I see that you updated the other Nginx Management doc link in [docs-ref-services/latest/mgmt-nginx-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/mgmt-nginx-readme.md), thank you. All of the checks have passed and I'll merge the pull request for you. The documentation updates should be on the live site Monday morning (it's updated every morning M-F now).

Thank you!

**Pull request merged**
