### PR TITLE
Message Fixes: User Story 1812099 - BULK

### PR DESCRIPTION
**Pull request by damabe**
Anyone notified by GitHub: this is for [user story 1812099](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1812099).

Addresses hard coded locales.

We are fixing issues related to Accessibility, SEO, and code blocks. You are welcome to review this PR, but for these changes, you don't need to sign off.

This is a bulk update.

Thanks -

### CODE REVIEW

**Review by danieljurek — APPROVED** [review]
LGTM

Since I'm new, here's what I looked at: 
* These are hand-written docs (won't affect our auto generated ref docs) 
* Validation passes without errors

**Comment by damabe** [comment]
#sign-off

**Comment by damabe** [comment]
#sign-off

This is a bulk update.

**Comment by damabe** [comment]
@danieljurek Do you know if this repo is set up to notify teams to merge with sign off? Or does someone need to do it manually? I don't have permissions to merge so if you can point me in the right direction, I can reach out and get it sorted.

**Comment by danieljurek** [comment]
@damabe - Is the `#signoff` meant to kick in some automation to merge the change? If so, I think adding the `auto-merge` tag to the PR will automatically merge it once there's a review signoff and associated checks have passed.

**Comment by damabe** [comment]
@danieljurek Yes. #sign-off (in other repos) kicks off a review process that ends with the PR being merged. I'm not familiar with adding tags and the subsequent review process in this repo.

**Comment by danieljurek** [comment]
I'm checking on the automation... In the meantime to get you unblocked I've approved this PR. Thanks!

**Comment by damabe** [comment]
@danieljurek Thank you!

**Pull request merged**
