### PR TITLE
Add redirect for broken link, update package overviews

### PR DESCRIPTION
**Pull request by mccoyp**
Resolves Azure/azure-sdk-for-python/issues/15796.

This also brings the package overviews up to date with azure-sdk-for-python READMEs.

### CODE REVIEW

**Comment by mccoyp** [comment]
@scbedd I can't seem to add you as a reviewer like a regular person so I'll tag you instead (I also don't have write access for merging, as a reminder)

**Review by scbedd — APPROVED** [review]
For the readme additions, please make certain that the updates are written to the source readmes as well!

**Comment by scbedd** [comment]
@mccoyp I added you to the `azure-sdk-team` under MicrosoftDocs. That will give you write access.

**Comment by mccoyp** [comment]
The readmes are now all in sync -- source was updated just before Christmas, so this was a good opportunity/reminder to update docs. Thank you!

**Comment by scbedd** [comment]
Merge it!

**Pull request merged**
