### PR TITLE
2/9 PM Publish

### PR DESCRIPTION
**Pull request by v-alje**

### CODE REVIEW

**Review by danieljurek — APPROVED** [review]

**Review by danieljurek — CHANGES_REQUESTED** [review]
Blocking this until I sort out the issues in the master branch.

**Comment by scbedd** [comment]
PR Submitted to adjust UI publishing so that the publishing crashes don't happen anymore.

**Comment by danieljurek** [comment]
Looks like we're getting stuck on errors in the same 3 generated files...


File | Status | Preview URL | Details
-- | -- | -- | --
docs-ref-autogen/azure-core/azure.core.CaseInsensitiveEnumMeta.yml | ❌Error |   | Details
docs-ref-autogen/azure-mgmt-servicebus/azure.mgmt.servicebus.models.MigrationConfigurationName.yml | ❌Error |   | Details
preview/docs-ref-autogen/azure-core/azure.core.CaseInsensitiveEnumMeta.yml | ❌Error |   | Details

**Comment by danieljurek** [comment]
Closing and reopening to trigger publishing validation.

**Review by danieljurek — APPROVED** [review]
Publishing validation unblocked

**Pull request merged**
