### PR TITLE
Update monitor-opentelemetry-exporter-readme.md

### PR DESCRIPTION
**Pull request by lzchen**
Add excerpt to help users decide on whether to use the distro or exporter. Also added data collection basics as a prerequisite read.

### CODE REVIEW

**Comment by lzchen** [comment]
#sign-off

**Comment by lzchen** [comment]
@scbedd can this be reviewed?

**Comment by scbedd** [comment]
Hey @lzchen these changes look good, but unfortunately what will happen is on the very next release, your changes will be wiped out!

The readme file you changed in this repo is auto-populated from [this readme file](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-monitor-opentelemetry-exporter/README.md) when we release a new version of the `azure-monitor-opentelemetry-exporter` package.

I will gladly sign off this review after you merge a PR to the repo w/ these same changes.

CC @danieljurek @JimSuplizio

**Comment by lzchen** [comment]
@scbedd 

Thanks for the headsup. I am already making the same changes in that README file in this [pr](https://github.com/Azure/azure-sdk-for-python/pull/34462. If this doc is indeed populated from that README file then I can close this PR.

**Pull request closed without merging**
