### PR TITLE
CC91861: Typo

### PR DESCRIPTION
**Pull request by v-makoud**
Hello, @lisawong19,
This proposed file change comes from https://github.com/MicrosoftDocs/azure-docs-sdk-python.es-ES/pull/3 .
Could you review this contribution and help to merge if agreed?
Many thanks in advance.

### CODE REVIEW

**Comment by mmacy** [comment]
LGTM. #sign-off

@Taojunshen can you merge, please? Thanks. -MM

**Comment by v-makoud** [comment]
#sign-off

**Comment by v-makoud** [comment]
Hi @Taojunshen can you merge this PR, please?

**Comment by v-makoud** [comment]
Hi @Taojunshen can you merge this PR, please?

**Pull request merged**
