### PR TITLE
Validation Code tag cleanup sdk python

### PR DESCRIPTION
**Pull request by TimShererWithAquent**
[1907184](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1907184)

No experience in this repo - it's public repo. We can follow up later.

### CODE REVIEW

**Comment by TimShererWithAquent** [comment]
@dbradish-microsoft And one more that is ready for review -

**Comment by dbradish-microsoft** [comment]
@TimShererWithAquent , please take out of draft mode and sign off.  Thank you.

**Comment by TimShererWithAquent** [comment]
#sign-off

**Comment by TimShererWithAquent** [comment]
@barbkess - Is there a procedure for getting PRs merged in this repo? - Thanks

**Comment by v-andreaco** [comment]
@herohua @barbkess 

Is there a particular process we need to follow to get PRs in this repo merged? I'm seeing both of you listed (in different places) as content/repo owners. If my information is incorrect, do you know who we should reach out to?

Thanks!

**Comment by TimShererWithAquent** [comment]
We closed the other PR for this repo - MicrosoftDocs/azure-docs-sdk-python/pull/1514

**Pull request closed without merging**
