### PR TITLE
Fix typo in get_send_status method name

### PR DESCRIPTION
**Pull request by PramodValavala-MSFT**
resolves Azure/azure-sdk-for-python#28408

### CODE REVIEW

**Comment by PramodValavala-MSFT** [comment]
@msyyc Could you please review and merge this? Thanks!

**Comment by PramodValavala-MSFT** [comment]
@msyyc I believe this is the wrong place to make this PR. So, I've made [this one](https://github.com/Azure/azure-sdk-for-python/pull/28485) on the main repo.

Could you confirm if I am right about this? If so, we can close this PR out.

**Comment by msyyc** [comment]
@PramodValavala-MSFT I merged https://github.com/Azure/azure-sdk-for-python/pull/28485 and let us see whether it can be resolved.

**Comment by PramodValavala-MSFT** [comment]
@msyyc Looks like the other PR didn't resolve it apart from having the README file updated in the repo. 😄

**Review by msyyc — APPROVED** [review]

**Comment by msyyc** [comment]
@PramodValavala-MSFT I don't have access to merge the PR. Maybe @danieljurek can help.

**Comment by danieljurek** [comment]
Package-level overview files are updated in the docs repo when the package releases. Opening PRs in both this repo and the SDK repo is the correct process if you want to fix an issue on the live docs without releasing a new package. I'll approve and merge this.

**Review by danieljurek — APPROVED** [review]

**Pull request merged**
