### PR TITLE
Typo "Azure SQL database"→"Azure SQL Database"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/python/api/overview/azure/sql?view=azure-python
#PingMSFTDocs

### CODE REVIEW

**Comment by danieljurek** [comment]
Hi @hyoshioka0128, thank you for your contribution. I'm looking for the right person to review these changes.

**Comment by danieljurek** [comment]
@ericshape, @jamestao would you please have a look at the style changes for this PR and approve if it can be released.

**Review by ericshape — APPROVED** [review]

**Comment by ericshape** [comment]
LGTM

**Review by danieljurek — APPROVED** [review]

**Comment by danieljurek** [comment]
@hyoshioka0128 -- Your PR is approved and I have merged it. Your changes will appear on docs.microsoft.com the next time we publish documents (probably next week). Thanks again for your contribution!

**Pull request merged**
