### PR TITLE
Add Track 2 packages to Preview TOC tree

### PR DESCRIPTION
**Pull request by nickzhums**
Hi Scott, this PR is to add Track 2 packages to python preview TOC tree

### CODE REVIEW

**Comment by scbedd** [comment]
I need to update `reference-unified.yml` with these changes, then I'll merge this. Thanks @nickzhums !

Why? We filter `reference-latest` and `reference-preview` down to only present namespaces in each moniker. This will become part of automation :D

**Comment by scbedd** [comment]
As a heads up, the actual onboarding piece is actually live now!

**Comment by nickzhums** [comment]
@scbedd  thanks ! does that mean i can merge this?

**Comment by scbedd** [comment]
I'm _generating_ the `reference-preview` and `reference-latest` ToCs from a single ToC: `reference-unified.yml`

What this does is allow me to automate the correct structure as packages are added and removed from preview! 

You're ok to merge this, I'm just pulling your changes into my copy of reference-unfied.

**Comment by scbedd** [comment]
If these changes get clobbered, they will be pulled in automatically by the same script. Just gotta wait for the new namespaces to show up.

**Comment by nickzhums** [comment]
@scbedd  got it,thanks

**Pull request merged**
