### PR TITLE
ms.custom tags for azure-docs-sdk-python

### PR DESCRIPTION
**Pull request by TimShererWithAquent**
[1907187](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1907187)

This PR contains updates to metadata tags only to support filters and reporting in the Content Performance Dashboard.

### CODE REVIEW

**Comment by TimShererWithAquent** [comment]
@dbradish-microsoft I'm leaving this in draft for now. There are build warnings that I don't understand. I think you can still verify my changes.

**Comment by dbradish-microsoft** [comment]
@TimShererWithAquent , updates look fine.  @DavidCBerry13  or @jess-johnson-msft might be able to assist with the build errors once this is taken out of Draft.

**Comment by TimShererWithAquent** [comment]
@DavidCBerry13 or @jess-johnson-msft 

Would one of you be the right person to reach out to about this issue? Any info would help - 

@dbradish-microsoft for awareness.

**Review by aurichh — APPROVED** [review]

**Comment by TimShererWithAquent** [comment]
Checking the status of the build.

**Comment by DavidCBerry13** [comment]
@TimShererWithAquent @dbradish-microsoft - Hold off on this for a bit.  Will reach out on Teams with more info

**Comment by TimShererWithAquent** [comment]
Closing per discussion with @DavidCBerry13 

@dbradish-microsoft for awareness.

**Pull request closed without merging**
