### PR TITLE
Cleaning up formatting and whitespace (to help with inventories)

### PR DESCRIPTION
**Pull request by kraigb**

### CODE REVIEW

**Comment by kraigb** [comment]
#sign-off

@sptramer @erickson-doug Can either of you merge this PR? Just cleaning up some stuff I found during inventory work.

**Comment by erickson-doug** [comment]
can you send me a pr link

--
Doug Erickson (douge) -- 425 273 1304

________________________________

**Comment by sptramer** [comment]
Tagging @rloutlaw to see if any of these files are touched in reference generation

**Comment by rloutlaw** [comment]
@sptramer Anything in docs-ref-conceptual and docs-ref-services isn't touched by the ref autogen-we don't mess with this. :)

**Pull request merged**
