### PR TITLE
Fix fusion toc reference config

### PR DESCRIPTION
**Pull request by TianqiZhang**

### CODE REVIEW

**Comment by TianqiZhang** [comment]
@scbedd did you get a chance to merge `smoke-test` to master?

**Comment by yishengjin1413** [comment]
@scbedd  Can you help to merge this PR now?

**Comment by TianqiZhang** [comment]
@scbedd @yishengjin1413 this PR is only config fix and it's should not have any dependency on smoke-test content. Can we merge this one first?

**Comment by yishengjin1413** [comment]
Merged.

**Pull request merged**
